### ISSUE TITLE
Cannot find graph "Generic by SNMP: Ping lost" used in dashboard "EdgeMAX: System Statistics".

### ISSUE THREAD

**Issue by notfixingit3** [albin-lindstrom/zabbix-edgemax-template#15]
Running into an issue with 6.0 template importing, I'm guessing I"m missing some other template that contains the graph but I'm just guessing?

Error on import: Cannot find graph "Generic by SNMP: Ping lost" used in dashboard "EdgeMAX: System Statistics".

**Comment by notfixingit3** [comment]
I got around this by adding the graphs by hand to the Generic By SNMP Template based on ICMP loss and ICMP response time

**Comment by kodiakastu** [comment]
Thank you. I will try to push an update to streamline the import
