### ISSUE TITLE
No Network Interface Discovery

### ISSUE THREAD

**Issue by DataCare-RobWilliams** [albin-lindstrom/zabbix-edgemax-template#8]
On Zabbix 5.2 using edge switch ES-24-Lite I cannot get any network interface information or memory information. Downloaded the MIBs and installed them on the zabbix server but I get many OID  not available errors on items and no network interface discovery using this template.

**Comment by albinbatman** [comment]
Hi @DataCare-RobWilliams,

I think the OIDs differ for the EdgeSwitches. This has been tested with EdgeRouters only.

Can you send me the MIB files for your EdgeSwitch?

**Comment by hyundaisantafe014** [comment]
Hii I have not txt temp with EdgeSwitch please send me its file
